services:
  UMSDB:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'NIKHIL'
    ports:
      - "9000:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
